spring:
  application:
    name: search-service

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:mysql://localhost:3306/booking_qa_db
    username: booking_qa_1
#    password: booking_qa_1#1
    password: ENC(uSH22SttzHked9mg06gefodFAQRPAvBB)

  jpa:
    hibernate:
      ddl-auto: update

jasypt:
  encryptor:
    password: salt

eureka:
  client:
    serviceUrl:
      defaultZone: http://myhost:8761/eureka/

logging:
  level:
    com:
      jdum:
        booking: DEBUG
